### ISSUE TITLE
Could this work on Ghost(Pro)?

### ISSUE THREAD

**Issue by WebShapedBiz** [ghostboard/ghost-purge-images#41]
Hi.

Is there a way to make it work on Ghost(Pro)?

Cheers.

**Comment by dburgos** [comment]
hello @WebShapedBiz 

It could work for anyone who can access the server but Ghost Pro is a managed service that does not provide server access to the customers. I found [this article](https://ghost.org/help/ssh-ftp-access/) in the Ghost documentation that would confirm it.

Anyway, no worries about that since Ghost Pro does not charge for the upload storage so far

![Captura de pantalla 2024-01-30 a las 18 43 08](https://github.com/ghostboard/ghost-purge-images/assets/1589874/d526cd40-2782-4b35-8871-e4ba8837e851)

Source: https://ghost.org/pricing/ (File Uploads tooltip)
